<?
$PERM["about"]["G8"]="D";
$PERM["about"]["*"]="D";
$PERM[".access.php"]["8"]="D";
$PERM["upload"]["8"]="D";
$PERM["store"]["8"]="D";
$PERM["search"]["8"]="D";
$PERM["personal"]["8"]="D";
$PERM["news"]["8"]="D";
$PERM["marketplace"]["8"]="D";
$PERM["login"]["8"]="D";
$PERM["include"]["8"]="D";
$PERM["images"]["8"]="D";
$PERM["cgi-bin"]["8"]="D";
$PERM["catalog"]["8"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["auth"]["8"]="D";
$PERM["index.php"]["8"]="W";
$PERM["/"]["*"]="R";
?>